// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import ()

type User struct {
	// id
	UserID uint32
	// ユーザー名
	UserName string
	// メールアドレス
	Email string
	// パスワード
	Password string
}
