// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ExistsUser(ctx context.Context, email string) (bool, error)
	GetLastInsertID(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
